- name: Create/Update the Cloudera Cloudformation stack
  cloudformation:
    stack_name: "{{app.name}}-stack"
    state: present
    disable_rollback: no
    template: "cf-generated-templates/stack-{{app.name}}-final"
    create_changeset: true
    changeset_name: "{{app.name}}_cf_changeset"
    tags:
      Stack: "{{app.name}}"          